### ISSUE TITLE
ImportFileDialog: column headers are not assigned properly to variable names

### ISSUE THREAD

**Issue by gernot-hochmuth** [gmrandazzo/QStudioMetrics#1]
importing csv tables (e.g. the example file "wine.csv") the column headers are not assigned properly to variable names. The header of the first column will get lost. The header of the second column will be assigned to the first variable name etc.. The last column will not get a variable name.  This seems to happen due to mis-indexing the headers when assigning the headers to the variable names.
In functions ```ImportFileDilog::ImportType0``` and ```ImportFileDilog::ImportType1``` the loop that assigns the header data to variable names should read:
```c++
for(int j = 0; j < header.size(); j++){
      AssignName(m->getVarName(), header[j]);
    }
```

**Comment by gmrandazzo** [comment]
Many thanks
