### ISSUE TITLE
file chartqt.cpp: QMouseEvent::localPos() deprecated in Qt-6

### ISSUE THREAD

**Issue by gernot-hochmuth** [gmrandazzo/QStudioMetrics#10]
https://github.com/gmrandazzo/QStudioMetrics/blob/0ae3147169eea2fa43f27783eade036c8e47c383/src/Chart/chartqt.cpp#L90
the call to member function`localPos()` for class `QMouseEvent` is deprecated when compiling with Qt-6. see:
[Qt-6 documentation of obsolete members for class QMouseEvent](https://doc.qt.io/qt-6/qmouseevent-obsolete.html#localPos)

> `QPointF QMouseEvent::localPos() const`
> This function is deprecated since 6.0. We strongly advise against using it in new code.
> Use `position()` instead.

The compiler complains with a warning about the use of the deprecated function.
Line 90 in file chartqt.cpp should be changed to
```C++
auto const widgetPos = event->position();
```
in order to enhance compatibility with Qt-6. But this change possibly breaks compatibility to Qt-5. please revise.

**Comment by gmrandazzo** [comment]
This code is now deprecated. A new version of the chart library based on QChart will be available soon.
