### ISSUE TITLE
Save session fails

### ISSUE THREAD

**Issue by tortorellas** [gmrandazzo/QStudioMetrics#20]
While trying to save a session, only an empty folder is created.
Reproducible in version 2.3.0 (Windows), libscientific 1.4.1

**Comment by gmrandazzo** [comment]
Thank you! Now fixed with the commit [52e1d27](https://github.com/gmrandazzo/QStudioMetrics/commit/52e1d278bf81337c8d7cb79edc89c28df89c1faa)
