### ISSUE TITLE
Enable "recent files" path

### ISSUE THREAD

**Issue by tortorellas** [gmrandazzo/QStudioMetrics#23]
File/Recent Files is empty

Reproducible in version 2.3.0 (Windows), libscientific 1.4.1

**Comment by gmrandazzo** [comment]
Issue fixed with commit https://github.com/gmrandazzo/QStudioMetrics/commit/e41e1dc62c04fac72c75012cc07553cc73e74ebb

**Comment by gmrandazzo** [comment]
Any project openbed  from "recent files list" will be automatically autosaved without the need of clicking "SaveAs" before closing the application.
