### ISSUE TITLE
Improve saving option

### ISSUE THREAD

**Issue by tortorellas** [gmrandazzo/QStudioMetrics#24]
Saving is tedious. An icon or shortcut to automatically overwrite the session (same path, same project name) would be helpful.

**Comment by gmrandazzo** [comment]
Issue fixed with commit https://github.com/gmrandazzo/QStudioMetrics/commit/e41e1dc62c04fac72c75012cc07553cc73e74ebb

**Comment by gmrandazzo** [comment]
Now, when you open a project session from your menu will automatically be saved every time you close the program. 
Moreover, if you do not save the project and you close by clicking quit or the "x," the program will ask you to save or not the project. If you decide to keep the project, this will also be added to the recent list before closing everything.
