### ISSUE TITLE
The usage of software

### ISSUE THREAD

**Issue by yueluming** [gmrandazzo/QStudioMetrics#4]
Well, I am interested in this work, and I got the software on the win10, but I do not know the compose of your standard data and how to use this software to deal with my own data. Could you give me a instructor to use it.
Thanks !

**Comment by gmrandazzo** [comment]
Hello, top!

What you need is a simple CSV file, comma separated value or tab separated value. Let's imagine that you want to compute a PLS model right?

Then in this CSV file you must have:

- Column names of first line
- Row names on first column

Note that the target column must be in the same CSV file and could be placed where you want. No need to be placed at the beginning or end of the CSV file.

How can you prepare this file?
You can use Excel or libreoffice or what you want.
What must be important is that your file is ok, without errors.

Here you can find more explanation with an example:

https://github.com/gmrandazzo/QStudioMetrics/wiki/Input-file-preparation

I hope this will help.
If not please feel free to reopen the issue. 

Many thanks.
