### ISSUE TITLE
Application crashes when plotting variable-vs-variable

### ISSUE THREAD

**Issue by gernot-hochmuth** [gmrandazzo/QStudioMetrics#5]
QStudiometrics Application crashes when plotting variable-plot (variable vs. variable). Source-code is most recent code available at github (V2.0.2) as of today. Recent changes to scatterplot-function may have introduced indexing or range error.
error message in terminal:
```bash
ScatterPlot F2
2D and 3D plot init
ASSERT failure in QVector<T>::remove: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h, line 457
Abgebrochen (Speicherabzug geschrieben)
```
please revise. thank you!

**Comment by gmrandazzo** [comment]
Many thanks. Yes.. I' m planning to recode the entire plot library. I will fix the issue in the next release.

**Comment by gernot-hochmuth** [comment]
with the latest changes to the plot library this issue has been resolved. Thank You!
