### ISSUE TITLE
error in PlotSettingsDialog.ui

### ISSUE THREAD

**Issue by gernot-hochmuth** [gmrandazzo/QStudioMetrics#7]
https://github.com/gmrandazzo/QStudioMetrics/blob/0ae3147169eea2fa43f27783eade036c8e47c383/src/Dialogs/PlotSettingsDialog.ui#L140-L146
I suspect line 143 should read
```XML
<string>x max</string>
```
please revise. thank you!

**Comment by gmrandazzo** [comment]
Fixed. Thanks!
